- go.mod
- go.sum
- services/management-api/init.go
The changes in this commit add support for logging to a file in addition to the standard output. The logging options can be configured through environment variables. The following environment variables are used:
- `LOG_TO_FILE`: Set to "true" to enable logging to file
- `LOG_FILENAME`: The path and filename of the log file
- `LOG_MAX_SIZE`: The maximum size of the log file in megabytes
- `LOG_MAX_AGE`: The maximum age of log files in days
- `LOG_MAX_BACKUPS`: The maximum number of log file backups to keep
- `LOG_LEVEL`: The log level to use (debug, info, warn, error)
If `LOG_TO_FILE` is set to "true", the log messages will be written to the specified file using the JSON format. Otherwise, the log messages will be written to the standard output.
The `initLogger` function is introduced to …
> feat: add support for logging to file with configurable options

- pkg/study/types/survey-item.go
Number input response could not be set, because "null" values were sent out, and that caused front-end checks to fail if input's min and max are undefined
> omit empty properties to avoid issue with number inputs

- pkg/apihelpers/parsePaginatedQuery.go
- pkg/study/exporter/survey-responses/parser.go
- pkg/study/exporter/survey-responses/utils.go
- pkg/study/participant-data.go
- services/management-api/apihandlers/study-management.go
Add the possibility for the response exporter to include extra context column names
Additionally, this PR fixes bugs for exporting metadata timestamps
> Extra ctx col names for exporter

- jobs/messaging/outgoing-messages.go
- jobs/messaging/scheduled-messages.go
In case somehow messages were generated with an empty `to` array, it caused them being stuck in the outgoing. This PR implements avoiding these cases, by preventing them to be added in first place, or removing them through the outgoing handler.
> Fix attempt sending emails to empty to list

- jobs/messaging/outgoing-messages.go
- pkg/messaging/email-sending/send.go
- pkg/messaging/types/outgoing_email.go
- pkg/user-management/user-management.go
- services/participant-api/apihandlers/authentication.go
- services/participant-api/apihandlers/utils.go
In case the smtp-bridge was not available, or for any other reason, some emails were queued up in the outgoing collection, and then the email sending resumed, all stuck messages were sent out at once. Often this resulted in receiving multiple verification codes that were already expired at once in a batch.
> Add expiration to outgoing emails

- pkg/permission-checker/constants.go
- services/management-api/apihandlers/handlers.go
- services/management-api/apihandlers/user-management.go
- services/management-api/init.go
- services/management-api/main.go
Implementing management functionality to delete participant users (and mark their participants deleted in the study system).
To enable this, the management-api service needs configuration to the participant-user-db and the global-infos db. 
The action to delete a participant-user can be performed by:
- admin users
- management-users with the permission: `users.*.delete-users`
In the environment variables, define following new entries:
- `PARTICIPANT_USER_DB_USERNAME`
- `PARTICIPANT_USER_DB_PASSWORD`
- `GLOBAL_INFOS_DB_USERNAME`
- `GLOBAL_INFOS_DB_PASSWORD`
In the `config.yaml` file define the variables (adapt values as it fits your setup):
```
...
db_configs:
participant_user_db:
connection_str: "<db-url>"
connection_prefix: "<empty or +srv>"
timeout: 30
idle_conn_timeout: 45 …
```
> Participant user deletion

- pkg/db/study/responses.go
- pkg/study/study-service.go
- pkg/study/studyengine/actions.go
Improve behaviour of replay action, so that it used actual arrivedAt attribute from the response to override the lastSubmissions list
> Reuse arrived at for response replay action

- pkg/study/helpers.go
- pkg/study/types/survey-item.go
- pkg/study/types/surveyResponse.go
This pull request introduces changes to support mapping confidential survey responses to a different key. The main updates include adding a `MapToKey` field to relevant structs and adjusting the logic to use this field when saving confidential data.
* Updated the `saveResponses` function to use the `MapToKey` field for confidential survey responses, ensuring the correct key is used when saving data.
* Added a `MapToKey` field to the `SurveyItem` struct to specify an alternate key for confidential mode.
* Added a `MapToKey` field to the `SurveyItemResponse` struct to support mapping to a different key in confidential mode.
> Map to key for confidential questions

- pkg/study/exporter/survey-responses/parser.go
- pkg/study/exporter/survey-responses/types.go
Changes to support `ArrivedAt` timestamp:
* Added `arrived` to the list of column names in `initColumnNames`.
* Included `ArrivedAt` in the `ParseResponse` function to capture the arrival time of a response.
* Updated `findSurveyVersion` call to use `ArrivedAt` instead of `SubmittedAt` for version lookup.
* Added `ArrivedAt` to the fixed columns in `initWithFixedColumnsWithValues`.
* Added `ArrivedAt` field to the `ParsedResponse` struct.
> exporter should use arrived at

- pkg/db/participant-user/otps.go
- pkg/user-management/user-management.go
- services/participant-api/apihandlers/authentication.go
- services/participant-api/apihandlers/user-management.go
Enforcing the limit to the number of OTPs that can be created for a user by using a transaction and incorporating random wait times to mitigate brute force attacks.
> Atomic otp creation with respecting limit

- pkg/study/studyengine/expressions.go
- pkg/study/studyengine/expressions_test.go
Migrating content of https://github.com/influenzanet/study-service/pull/31
* Added `sum` function to evaluate the sum of numeric and boolean expressions. 
* Added `neg` function to evaluate the negation of a numeric expression.
* Modified `hasEventPayload` function to simplify the return statement by removing unnecessary nil check. 
* Added `TestEvalHasEventPayload` to verify the behavior of `hasEventPayload` function. 
* Added `TestEvalSum` to verify the behavior of the `sum` function with various inputs. 
* Added `TestEvalNeg` to verify the behavior of the `neg` function with various inputs.
> Include sum and neg exps

- pkg/study/studyengine/actions.go
- pkg/study/studyengine/actions_test.go
- pkg/study/studyengine/expressions.go
- pkg/study/studyengine/expressions_test.go
- pkg/study/studyengine/helpers.go
This pull request introduces a new `Now` function to replace direct calls to `time.Now()` throughout the `studyengine` package. This change improves testability by allowing the current time to be overridden in tests. The most important changes include modifying various functions to use the new `Now` function and updating tests to leverage this functionality.
(Replicate changes from https://github.com/influenzanet/study-service/pull/32)
> Study engine now

- services/management-api/apihandlers/study-management.go
* Changed the HTTP method from `GET` to `POST` for starting export generation for responses in `addStudyDataExporterEndpoints` function.
* Changed the HTTP method from `GET` to `POST` for starting export generation for participants in `addStudyDataExporterEndpoints` function.
* Changed the HTTP method from `GET` to `POST` for starting export generation for reports in `addStudyDataExporterEndpoints` function.
Recommendation from security screening (ID: NCC-E012650-CAT)
> GET requests are not protected by CSRF controls and may be abused by an attacker to perform that action.
* Simplified the conditional check for `respItem.Items` in the `parseSlots` function by removing the `nil` check.
> change to POST

- jobs/messaging/participant-messages.go
This pull request includes a change to the `handleParticipantMessages` function in the `jobs/messaging/participant-messages.go` file. The change involves adding participant flags to the payload when generating email content.
Improvements to payload handling:
* [`jobs/messaging/participant-messages.go`](diffhunk://#diff-be928a8c7070f8c14eb1d7e07dcb7392b0174545a3e3d58b66d4529538af03a0R105-R109): Added a loop to include participant flags into the payload before generating email content.
To use a flag value in the template, use:
`{{ index . "flags.<keyOfTheFlag>"}}`
E.g.: `{{ index . "flags.inviteCode"}}`
> make participant flags available by templates

- .gitignore
- jobs/messaging/init.go
- jobs/study-daily-data-export/init.go
- jobs/study-timer/init.go
- jobs/user-management/init.go
- pkg/utils/logUtils.go
- services/management-api/init.go
- services/participant-api/init.go
- services/smtp-bridge/init.go
This pull request introduces significant updates to the logging configuration across multiple services. The changes include adding support for including build information in logs, refactoring the logger initialization, and updating configurations to accommodate these new features.
- removing the possibility to configure logging through env variables for the management-api
- the env variables are not used anymore (can be removed):  `LOG_TO_FILE, LOG_FILENAME, LOG_MAX_SIZE, LOG_MAX_AGE, LOG_MAX_BACKUPS, LOG_LEVEL, LOG_INCLUDE_SRC`
- in the config.yaml include the logging configs:
```
...
logging:
log_level: "debug"
include_src: true
log_to_file: true
filename: "./logs/management-api.log"
max_size: 1
max_backups: 100
max_age: 28
compress_old_logs: true
include_build_info: "always"
... 
``` …
> logging can use a build-info.yaml file to output extra infos

- services/smtp-bridge-emulator/init.go
- services/smtp-bridge/init.go
This pull request includes changes to the `services/smtp-bridge-emulator/init.go` and `services/smtp-bridge/init.go` files to add functionality for overriding API keys from environment variables. The most important changes include adding the `overrideFromEnv` function and updating the initialization process to call this function.
Enhancements to environment variable handling:
* [`services/smtp-bridge-emulator/init.go`](diffhunk://#diff-c689b67aedc91055a86e327fdceadb1c2ead674389a17f61cbfb23641c64fbc4R75-R87): Added `overrideFromEnv` function to override secrets from environment variables and updated the initialization process to call this function. [[1]](diffhunk://#diff-c689b67aedc91055a86e327fdceadb1c2ead674389a17f61cbfb23641c64fbc4R75-R87) …
> can override api keys from env variable

- pkg/study/exporter/survey-responses/questionTypeHandlers.go
- pkg/study/exporter/survey-responses/questionTypeUtils.go
This pull request includes changes to the `pkg/study/exporter/survey-responses` package, focusing on improving the handling of survey responses. The most important changes include adding conditions for matrix dropdown and radio row types, and removing redundant checks in the `parseSimpleCloze` and `parseClozeList` functions.
Improvements to survey response handling:
* [`pkg/study/exporter/survey-responses/questionTypeHandlers.go`](diffhunk://#diff-97bbdc712de1e8329bdc38ec78e6d4aa327ef244d2045a8653cd05852cab6b3fR308): Added conditions to handle `QUESTION_TYPE_MATRIX_DROPDOWN` and `QUESTION_TYPE_MATRIX_RADIO_ROW` in the `ParseResponse` method. [[1]](diffhunk://#diff-97bbdc712de1e8329bdc38ec78e6d4aa327ef244d2045a8653cd05852cab6b3fR308) …
> Exporter fix matrix & cloze

- pkg/study/exporter/survey-responses/parser.go
- pkg/study/exporter/survey-responses/utils.go
This pull request includes changes to the `pkg/study/exporter/survey-responses` package to handle newline characters in survey responses. The intention behind this change is to allow a wider range of CSV parsers / software, to correctly and simply import response export files.
Improvements to handling newline characters:
* [`pkg/study/exporter/survey-responses/utils.go`](diffhunk://#diff-0a3c370af351650b6d16c1b55537f67342643899cc8e4f7bef72ca61c5bca162R53-R58): Added a new function `replaceNewlines` to replace newline characters with `<br />` in strings.
Updates to existing methods:
* [`pkg/study/exporter/survey-responses/parser.go`](diffhunk://#diff-2194e410de996ffdb5b9a0a51609e4d63c1ee5aa4f82b179ab7aeee17d967a09L193-R195): Updated the `ResponseToStrList` method to use the new …
> replace linebreaks with tag in csv export

- pkg/db/study/db.go
- pkg/db/study/study-code-lists.go
- pkg/permission-checker/constants.go
- pkg/study/exporter/survey-definition/compToResponseDef.go
- pkg/study/studyengine/actions.go
- pkg/study/studyengine/expressions.go
- pkg/study/studyengine/expressions_test.go
- pkg/study/studyengine/types.go
- pkg/study/types/study-code-list.go
- services/management-api/apihandlers/study-management.go
- services/participant-api/apihandlers/study-service.go
This pull request introduces functionality for managing study code lists in the study database. This can be used, e.g., to check if a user has an entry code, or a valid id code through a questionnaire.
* Added a new constant `COLLECTION_NAME_STUDY_CODE_LISTS` to define the collection name for study code lists.
* Created the `collectionStudyCodeLists` function to access the study code lists collection.
* Implemented the `CreateIndexForStudyCodeListsCollection` function to create indexes on the study code lists collection.
* **In order to guarantee unique codes per study code list, run the index creation method for the study DB or create the index manually (studyKey, listKey, code, with option unique)**
* Added functions to add, retrieve, and delete study code list entries, such as …
> Study wide code lists

- jobs/messaging/participant-messages.go
- pkg/study/participant-data.go
- pkg/study/studyengine/actions.go
- pkg/study/studyengine/expressions.go
- pkg/study/types/participant.go
- services/participant-api/apihandlers/study-service.go
This pull request introduces a new feature to handle linking codes for participants in a study. The changes include adding functions to set, delete, and retrieve linking codes, as well as updating the participant structure to include linking codes.
* [`jobs/messaging/participant-messages.go`](diffhunk://#diff-be928a8c7070f8c14eb1d7e07dcb7392b0174545a3e3d58b66d4529538af03a0R110-R114): Added logic to include linking codes in the payload when handling participant messages.
* [`pkg/study/participant-data.go`](diffhunk://#diff-7c6e7b6c2f80ffb4d32e61e256994417453cf337390adf0012dac6ef4d1c842fR476-R507): Introduced the `GetLinkingCode` function to retrieve linking codes for a participant.
* [`pkg/study/studyengine/actions.go`](diffhunk://#diff-d41cc7f9a23a22f49f27038120fcd5d54e203706fc2470ac7feb46 …
> Participant linking codes

- services/participant-api/apihandlers/user-management.go
This pull request includes an update to the `updateContactPreferences` function in the `services/participant-api/apihandlers/user-management.go` file. The main change is the addition of a new field to handle the weekly subscription toggle.
Changes to update contact preferences:
* Added a new field `ToggleWeeklySubscription` to the request struct to handle toggling the weekly subscription.
* Implemented logic to toggle the weekly subscription status based on the new `ToggleWeeklySubscription` field.
> feat (participant-api): add toggle for weekly subscription in contact preferences

- jobs/study-daily-data-export/confidential-resp-exporter.go
- jobs/study-daily-data-export/init.go
- jobs/study-daily-data-export/main.go
- jobs/study-daily-data-export/response-exporter.go
- pkg/db/study/confidentialResponses.go
- services/management-api/apihandlers/study-management.go
This pull request introduces a new feature for exporting confidential survey responses and refactors the existing response export functionality. The most important changes include adding new types for export tasks, implementing functions for exporting confidential responses, and refactoring the existing response export logic to improve maintainability.
In order to be able to reuse the exporter job for multiple file formats, and other usability considerations, the config structure was changed. Please update the config.yaml file. 
Old format:
```
...
response_exports:
export_path: "storage/daily-exports"
retention_days: 365
override_old: false
export_format: "json"
short_keys: true
separator: "-"
sources:
- instance_id: "<instanceID>"
study_key: "<studyKey>"
survey_keys: ["<survey1>", …
```
> Daily exporter features

- jobs/user-management/generate-id-lookup.go
- jobs/user-management/init.go
- jobs/user-management/main.go
- pkg/db/study/db.go
- pkg/study/study-service.go
This pull request introduces a new feature for generating a profile ID lookup and includes several other related changes. The most important changes include the addition of the `generateProfileIDLookup` function, updates to the configuration structure to include new tasks, modifications to the main execution flow to support the new tasks, and enhancements to database indexing and error handling.
New section needed to run the different tasks included in the job:
```
run_tasks:
clean_up_unverified_users: true
send_reminder_to_confirm_accounts: true
handle_inactive_users: true
generate_profile_id_lookup: false
```
The job currently supports 4 tasks:
- previously the first 3 task were running by default when the job started. Logic for these did not change, only that now they need to be …
> Generate pid lookup

- pkg/db/global-infos/temptoken.go
- pkg/db/management-user/db.go
- pkg/db/management-user/management-users.go
- pkg/db/management-user/permissions.go
- pkg/db/management-user/service-users.go
- pkg/db/management-user/sessions.go
- pkg/db/messaging/db.go
- pkg/db/messaging/sent-sms.go
- pkg/db/participant-user/failedOtpAttempts.go
- pkg/db/participant-user/otps.go
- pkg/db/participant-user/renew-tokens.go
- pkg/db/participant-user/users.go
- pkg/db/study/db.go
- pkg/db/study/participants.go
- pkg/db/study/reports.go
- pkg/db/study/responses.go
- pkg/db/study/study-code-lists.go
- pkg/db/study/studyInfos.go
- pkg/db/study/studyRules.go
- pkg/db/study/surveys.go
In many cases, there are error messages about existing index with different names or options. To ensure the right indexes are present, when using the DB init with index creation option, it will first drop all indexes on the collection before adding the specified indexes. 
If the setup is using manually added indexes, don't use the auto index creation because it will now remove the manually added ones.
* **Global Infos:**
* Added logging for errors when dropping indexes in `CreateIndexForTemptokens` function. (`pkg/db/global-infos/temptoken.go`)
* **Management User:**
* Refactored index creation into separate functions (`createIndexForManagementUsers`, `createIndexForPermissions`, `createIndexForSessions`, etc.) and added error logging for index dropping operations. …
> Drop db indexes before creating

- pkg/study/participant-data.go
- pkg/study/studyengine/actions.go
- pkg/study/studyengine/expressions.go
This pull request is focusing on improving the handling of survey prefill rules. The most important changes include adding a new function to remove non-existing prefill slots, modifying the `resolvePrefillRules` function, and refactoring the method calls in the `studyengine` package.
* Added a new function `removeNonExistingPrefillSlots` to clean up prefill slots that do not exist in the survey definition (`pkg/study/participant-data.go`).
* Modified the `resolvePrefillRules` function to handle the new prefill item type `PREFILL_ITEM_WITH_LAST_RESPONSE` and added a time filter resolution (`pkg/study/participant-data.go`).
* Changed all instances of `EvalContext.expressionArgResolver` to `EvalContext.ExpressionArgResolver` in the `studyengine` package for consistency …
> Prefill improvements

- pkg/db/study/study-code-lists.go
- pkg/db/study/studyInfos.go
- pkg/study/studyengine/actions.go
- pkg/study/studyengine/expressions_test.go
- pkg/study/studyengine/types.go
- services/management-api/apihandlers/study-management.go
This pull request introduces several new functionalities and improvements to the study code management system. The most significant changes include the addition of methods for deleting study code list entries, drawing study codes, and handling new actions related to study codes.
* Added `DeleteStudyCodeListEntries` method to delete multiple study code list entries based on `studyKey` and `listKey`.
* Added `DeleteStudyCodeListsForStudy` method to delete all study code lists for a given study.
* Added `DrawStudyCode` method to draw and delete a study code from a list.
* Modified `removeStudyCodeListEntryHandler` to handle the deletion of entire study code lists if no specific code is provided. [[1]](diffhunk://#diff-1021fc6f3e5d0784378aca1a5b347f96b5e9cc46c8a31593001156d3d935a1f4L1662-R1677 …
> Study code list improvements

- jobs/study-timer/init.go
- jobs/study-timer/main.go
- pkg/db/study/taskQueue.go
- If configured, it can remove orphaned task result files to optimise disk usage. Tasks are deleted after two days, so files after two days become orphaned and likely be never used by the admin-ui. 
- To configure, add the following snippet to the config.yaml:
```
...
clean_up_config:
filestore_path: "<path-to-storage-location>"
clean_orphaned_task_results: true
```
- It will scan the path at `<filestore_path>/<instance_id>` recursively for files (for each instance ID defined in the `instance_ids` array in the config.yaml)
- for each file found, it will check if a corresponding "task" object still exists in the database
- if no task object was found, the file will be removed
> Delete orphan task result files

- jobs/study-daily-data-export/init.go
- jobs/study-daily-data-export/main.go
- jobs/study-timer/main.go
- pkg/study/utils/cleanup-orphaned-exports.go
This pull request introduces a new feature for cleaning up orphaned task results and refactors existing code to utilize this new functionality. The main changes include adding a new configuration structure, updating the `main` functions in two files to call the new cleanup method, and moving the cleanup logic to a new utility file.
Key changes:
* Added `CleanUpConfig` struct to the configuration in `jobs/study-daily-data-export/init.go` to enable cleanup settings.
* Updated `main` function in `jobs/study-daily-data-export/main.go` to run the cleanup process if enabled in the configuration.
* Updated `main` function in `jobs/study-timer/main.go` to call the new cleanup method from the utility package.
To use the new feature, add the following to the study-daily-data-export job's config: …
> Delete old task result files by daily exporter

- pkg/study/studyengine/expressions.go
- pkg/study/studyengine/expressions_test.go
This pull request introduces a new function `getTsForNextStartOfMonth` in the `EvalContext` class to calculate the timestamp for the start of the next specified month. It also includes corresponding tests for this new function to ensure its correctness. The most important changes are listed below:
* Added the `getTsForNextStartOfMonth` function to the `EvalContext` class in `pkg/study/studyengine/expressions.go`. This function calculates the timestamp for the start of the next occurrence of a specified month, given either a month name or number, and an optional reference timestamp. [[1]](diffhunk://#diff-016090a23f0a180705062387f40b3b376fc78cbed582903cfc30f5fbac2d3f2fR144-R145) [[2]](diffhunk://#diff-016090a23f0a180705062387f40b3b376fc78cbed582903cfc30f5fbac2d3f2fR1531-R1619)
* Added a …
> Study expression for next first of month

- services/participant-api/apihandlers/study-service.go
This pull request includes changes to the `services/participant-api/apihandlers/study-service.go` file, primarily to add a new API endpoint for retrieving participant state information. The changes include adding a new route and implementing the corresponding handler function.
* Added a new GET route for `/participant-state` in the `AddStudyServiceAPI` function. This endpoint requires a `pid` query parameter to specify the participant profile ID.
* Implemented the `getParticipantState` function to handle requests to the new `/participant-state` endpoint. This function performs several checks and retrieves the participant state from the database.
> implement endpoint to fetch participant state for a profile

- jobs/study-daily-data-export/confidential-resp-exporter.go
- pkg/study/utils/confidential-response-export.go
- services/management-api/apihandlers/study-management.go
- services/participant-api/apihandlers/study-service.go
This pull request refactors the confidential responses export functionality by moving related types and functions to a new utility package and updating the references accordingly. Additionally, it introduces a new endpoint for fetching confidential responses.
Refactoring and code organization:
* [`jobs/study-daily-data-export/confidential-resp-exporter.go`](diffhunk://#diff-fd43ff28dd192ef60ae72574f44feb1a6a77fe838d43ca7c1c7ae9647746b97cL18-L24): Removed the `ConfidentialResponsesExportEntry` struct and related functions, and replaced them with references to `studyutils.ConfidentialResponsesExportEntry` and `studyutils.PrepConfidentialResponseExport`. [[1]](diffhunk://#diff-fd43ff28dd192ef60ae72574f44feb1a6a77fe838d43ca7c1c7ae9647746b97cL18-L24) …
> Endpoint to fetch confidential data

- pkg/messaging/templates/utils.go
- services/management-api/apihandlers/messaging-service.go
This pull request introduces improvements to the handling of `MessageType` and adds validation for `studyKey` in the messaging service. The primary changes include sanitizing `MessageType` to ensure URL safety, validating the existence of `studyKey` before processing, and applying URL encoding to `messageType` parameters in relevant endpoints.
* Introduced a new function `SanitizeMessageType` in `pkg/messaging/templates/utils.go` to sanitize `MessageType` by trimming spaces, removing quotes and line breaks, and applying URL encoding.
* Updated `saveGlobalMessageTemplate` and `saveStudyMessageTemplate` in `services/management-api/apihandlers/messaging-service.go` to sanitize `MessageType` using the new function before further processing. …
> Improved study email template validation

- services/management-api/init.go
- services/management-api/main.go
This pull request refactors the configuration structure for the `management-api` service to improve organization and maintainability. The primary changes include grouping Gin-related configurations into a nested structure, integrating Mutual TLS (mTLS) settings within the Gin configuration, and updating references throughout the codebase to align with the new structure.
* Consolidated Gin-related settings (`DebugMode`, `AllowOrigins`, `Port`) into a nested `GinConfig` struct within the `Config` struct. This also includes a new nested `MTLS` struct for mTLS-specific settings. (`services/management-api/init.go`, [services/management-api/init.goL73-L86](diffhunk://#diff-51858c51b8105d269992321594e916678c1b3db308fbd2f3f67621f2d77e8064L73-L86))
* Removed redundant top-level mTLS environment …
> refactor: restructure configuration for Gin and Mutual TLS settings

- pkg/db/study/participants.go
- pkg/permission-checker/constants.go
- pkg/study/types/participant.go
- services/management-api/apihandlers/study-management.go
This pull request introduces functionality to update participant states in a study management system while ensuring data consistency. Key changes include adding a new API endpoint, updating the participant data model, and implementing a database method to handle conditional updates.
* Added a new method `UpdateParticipantIfNotModified` in `StudyDBService` to update participant states only if the `ModifiedAt` timestamp has not been changed since the last fetch. This ensures data consistency during concurrent updates. (`pkg/db/study/participants.go`, [pkg/db/study/participants.goR79-R108](diffhunk://#diff-f51ad8036e23e7fbb281ae5f48ffd33948ca9704407aab31c3c7c76e6b3569a0R79-R108))
* Updated the `Participant` struct to include a `ModifiedAt` field, which tracks the last modification timestamp …
> Update participant api

- pkg/study/types/expression.go
- services/management-api/apihandlers/study-management.go
This pull request introduces a new feature for exporting study configurations, along with some structural improvements and dependency updates. The most significant changes include adding a new API endpoint for exporting study configurations, implementing a helper struct for streaming JSON responses, and updating the `Expression` struct to use a pointer for its `Metadata` field.
* **New API Endpoint**: Added a `GET /export-config` endpoint to allow authorized users to export study configurations, surveys, and rules as a JSON file. This includes query parameters to specify which parts of the study to include in the export. (`services/management-api/apihandlers/study-management.go`, [services/management-api/apihandlers/study-management.goR102-R112](diffhunk://#diff-1021fc6f3e5d0784378aca1a5b3 …
> Export import studies
